### ISSUE TITLE
Deleted issue.

### ISSUE THREAD

**Issue by ghost** [p0l1t1c1an/bsdfan-rs#3]
Deleted issue.

**Comment by p0l1t1c1an** [comment]
Note: Sorry. I am not actively monitoring this repo anymore, so you can disregard this if you have gotten your issue fixed, or you have given up on BSD.

First of all, this repo is for a solution for fan control under one specific type of laptop. That being ThinkPads.
I know nothing about the set-up you have or how it works.  Below is what I have come with.

## Possible Solutions
#### Active Solutions:
- You may be able to enter your BIOS and set some option to control your fan through the BIOS and not the OS. 
  - That's how I fixed a similar issue for my desktop
  - You would not be able to adjust the settings on the fly
  - I don't know if this works with the GPU fan
- You could try to modify that program if there is someway to communicate to the EC in BSD
- `Powerd` if you do not have that set up

#### Passive Solutions
- Reddit, which you already did, and were given the answer of using `nvidia-settings`
- FreeBSD forums, if your email won't work, try an email alias service.
- Email some developers of FreeBSD 
  - Please be professional and clear with them or anyone else you ask, unlike what you said above


## Formatting your issues
The way you expressed your issue is a little nonsensical and rambles off. 
You should try to have an order to what you are saying when you need help. 
People who are trying to help are going out of their way, so try to make it as easy as possible for them to understand you.

#### Recommended Structure
- **What you are using**
  - Like hardware you are using
  - OS or related software
- **The problem**
  - Tell me in detail what is wrong 
    - What were you trying to do, and how did the outcome differ? (And more if relevant)
  - Do you suspect a certain issue
- **What have you tried**
  - List off each thing you can remember doing
  - Tell me what in detail for each one that you attempted


You should adapt this or some other format you like when asking for help.
It gives the person background to the issue, the goal you want, and knowledge on what not to suggest.

**Comment by uncharted-user** [comment]
Thanks for the reply. Yes, I have given up not only because of the lack of fan control issue but also another which is lack of NVIDIA CUDA support for PyTorch discovered recently. BIOS solution is non-existence for my Laptop. I tried all the passive solutions you mentioned, but nothing was helpful regarding EC. Yes, I would have formatted similar to your structure if it was an issue in your repo. My intention was more like an informal discussion to get some hint, as you also worked in that area.
